// Generated by rstantools.  Do not edit by hand.

/*
    trystan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    trystan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with trystan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_Pooled_Hybrid_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_Pooled_Hybrid");
    reader.add_event(130, 128, "end", "model_Pooled_Hybrid");
    return reader;
}
#include <stan_meta_header.hpp>
class model_Pooled_Hybrid
  : public stan::model::model_base_crtp<model_Pooled_Hybrid> {
private:
        int NE;
        int NF;
        std::vector<int> MT;
        int nMT;
        std::vector<int> FE;
        std::vector<int> R;
        int nrep;
        std::vector<double> tl;
        std::vector<double> logit_fn_rep;
        std::vector<double> fn_se;
        std::vector<std::vector<double> > Avg_Reads;
public:
    model_Pooled_Hybrid(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_Pooled_Hybrid(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_Pooled_Hybrid_namespace::model_Pooled_Hybrid";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "NE", "int", context__.to_vec());
            NE = int(0);
            vals_i__ = context__.vals_i("NE");
            pos__ = 0;
            NE = vals_i__[pos__++];
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "NF", "int", context__.to_vec());
            NF = int(0);
            vals_i__ = context__.vals_i("NF");
            pos__ = 0;
            NF = vals_i__[pos__++];
            current_statement_begin__ = 11;
            validate_non_negative_index("MT", "NE", NE);
            context__.validate_dims("data initialization", "MT", "int", context__.to_vec(NE));
            MT = std::vector<int>(NE, int(0));
            vals_i__ = context__.vals_i("MT");
            pos__ = 0;
            size_t MT_k_0_max__ = NE;
            for (size_t k_0__ = 0; k_0__ < MT_k_0_max__; ++k_0__) {
                MT[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "nMT", "int", context__.to_vec());
            nMT = int(0);
            vals_i__ = context__.vals_i("nMT");
            pos__ = 0;
            nMT = vals_i__[pos__++];
            current_statement_begin__ = 13;
            validate_non_negative_index("FE", "NE", NE);
            context__.validate_dims("data initialization", "FE", "int", context__.to_vec(NE));
            FE = std::vector<int>(NE, int(0));
            vals_i__ = context__.vals_i("FE");
            pos__ = 0;
            size_t FE_k_0_max__ = NE;
            for (size_t k_0__ = 0; k_0__ < FE_k_0_max__; ++k_0__) {
                FE[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 14;
            validate_non_negative_index("R", "NE", NE);
            context__.validate_dims("data initialization", "R", "int", context__.to_vec(NE));
            R = std::vector<int>(NE, int(0));
            vals_i__ = context__.vals_i("R");
            pos__ = 0;
            size_t R_k_0_max__ = NE;
            for (size_t k_0__ = 0; k_0__ < R_k_0_max__; ++k_0__) {
                R[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 15;
            context__.validate_dims("data initialization", "nrep", "int", context__.to_vec());
            nrep = int(0);
            vals_i__ = context__.vals_i("nrep");
            pos__ = 0;
            nrep = vals_i__[pos__++];
            current_statement_begin__ = 16;
            validate_non_negative_index("tl", "nMT", nMT);
            context__.validate_dims("data initialization", "tl", "double", context__.to_vec(nMT));
            tl = std::vector<double>(nMT, double(0));
            vals_r__ = context__.vals_r("tl");
            pos__ = 0;
            size_t tl_k_0_max__ = nMT;
            for (size_t k_0__ = 0; k_0__ < tl_k_0_max__; ++k_0__) {
                tl[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 17;
            validate_non_negative_index("logit_fn_rep", "NE", NE);
            context__.validate_dims("data initialization", "logit_fn_rep", "double", context__.to_vec(NE));
            logit_fn_rep = std::vector<double>(NE, double(0));
            vals_r__ = context__.vals_r("logit_fn_rep");
            pos__ = 0;
            size_t logit_fn_rep_k_0_max__ = NE;
            for (size_t k_0__ = 0; k_0__ < logit_fn_rep_k_0_max__; ++k_0__) {
                logit_fn_rep[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 18;
            validate_non_negative_index("fn_se", "NE", NE);
            context__.validate_dims("data initialization", "fn_se", "double", context__.to_vec(NE));
            fn_se = std::vector<double>(NE, double(0));
            vals_r__ = context__.vals_r("fn_se");
            pos__ = 0;
            size_t fn_se_k_0_max__ = NE;
            for (size_t k_0__ = 0; k_0__ < fn_se_k_0_max__; ++k_0__) {
                fn_se[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 19;
            validate_non_negative_index("Avg_Reads", "NF", NF);
            validate_non_negative_index("Avg_Reads", "nMT", nMT);
            context__.validate_dims("data initialization", "Avg_Reads", "double", context__.to_vec(NF,nMT));
            Avg_Reads = std::vector<std::vector<double> >(NF, std::vector<double>(nMT, double(0)));
            vals_r__ = context__.vals_r("Avg_Reads");
            pos__ = 0;
            size_t Avg_Reads_k_0_max__ = NF;
            size_t Avg_Reads_k_1_max__ = nMT;
            for (size_t k_1__ = 0; k_1__ < Avg_Reads_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < Avg_Reads_k_0_max__; ++k_0__) {
                    Avg_Reads[k_0__][k_1__] = vals_r__[pos__++];
                }
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 23;
            validate_non_negative_index("alpha", "NF", NF);
            num_params_r__ += NF;
            current_statement_begin__ = 24;
            num_params_r__ += 1;
            current_statement_begin__ = 25;
            num_params_r__ += 1;
            current_statement_begin__ = 26;
            validate_non_negative_index("log_sig_e", "(nMT - 1)", (nMT - 1));
            num_params_r__ += (nMT - 1);
            current_statement_begin__ = 27;
            validate_non_negative_index("mu_e", "(nMT - 1)", (nMT - 1));
            num_params_r__ += (nMT - 1);
            current_statement_begin__ = 30;
            validate_non_negative_index("z_fn", "NF", NF);
            validate_non_negative_index("z_fn", "nMT", nMT);
            validate_non_negative_index("z_fn", "nrep", nrep);
            num_params_r__ += (((1 * NF) * nMT) * nrep);
            current_statement_begin__ = 31;
            validate_non_negative_index("a", "nMT", nMT);
            num_params_r__ += nMT;
            current_statement_begin__ = 32;
            validate_non_negative_index("b", "nMT", nMT);
            num_params_r__ += nMT;
            current_statement_begin__ = 33;
            validate_non_negative_index("eff", "(nMT - 1)", (nMT - 1));
            validate_non_negative_index("eff", "NF", NF);
            num_params_r__ += ((nMT - 1) * NF);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_Pooled_Hybrid() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 23;
        if (!(context__.contains_r("alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        validate_non_negative_index("alpha", "NF", NF);
        context__.validate_dims("parameter initialization", "alpha", "vector_d", context__.to_vec(NF));
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha(NF);
        size_t alpha_j_1_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            alpha(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 24;
        if (!(context__.contains_r("mu_fn")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_fn missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_fn");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu_fn", "double", context__.to_vec());
        double mu_fn(0);
        mu_fn = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu_fn);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_fn: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 25;
        if (!(context__.contains_r("log_sig_fn")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable log_sig_fn missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("log_sig_fn");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "log_sig_fn", "double", context__.to_vec());
        double log_sig_fn(0);
        log_sig_fn = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(log_sig_fn);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable log_sig_fn: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 26;
        if (!(context__.contains_r("log_sig_e")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable log_sig_e missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("log_sig_e");
        pos__ = 0U;
        validate_non_negative_index("log_sig_e", "(nMT - 1)", (nMT - 1));
        context__.validate_dims("parameter initialization", "log_sig_e", "vector_d", context__.to_vec((nMT - 1)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> log_sig_e((nMT - 1));
        size_t log_sig_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < log_sig_e_j_1_max__; ++j_1__) {
            log_sig_e(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(log_sig_e);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable log_sig_e: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 27;
        if (!(context__.contains_r("mu_e")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_e missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_e");
        pos__ = 0U;
        validate_non_negative_index("mu_e", "(nMT - 1)", (nMT - 1));
        context__.validate_dims("parameter initialization", "mu_e", "vector_d", context__.to_vec((nMT - 1)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> mu_e((nMT - 1));
        size_t mu_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < mu_e_j_1_max__; ++j_1__) {
            mu_e(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(mu_e);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_e: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 30;
        if (!(context__.contains_r("z_fn")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable z_fn missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("z_fn");
        pos__ = 0U;
        validate_non_negative_index("z_fn", "NF", NF);
        validate_non_negative_index("z_fn", "nMT", nMT);
        validate_non_negative_index("z_fn", "nrep", nrep);
        context__.validate_dims("parameter initialization", "z_fn", "double", context__.to_vec(NF,nMT,nrep));
        std::vector<std::vector<std::vector<double> > > z_fn(NF, std::vector<std::vector<double> >(nMT, std::vector<double>(nrep, double(0))));
        size_t z_fn_k_0_max__ = NF;
        size_t z_fn_k_1_max__ = nMT;
        size_t z_fn_k_2_max__ = nrep;
        for (size_t k_2__ = 0; k_2__ < z_fn_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < z_fn_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < z_fn_k_0_max__; ++k_0__) {
                    z_fn[k_0__][k_1__][k_2__] = vals_r__[pos__++];
                }
            }
        }
        size_t z_fn_i_0_max__ = NF;
        size_t z_fn_i_1_max__ = nMT;
        size_t z_fn_i_2_max__ = nrep;
        for (size_t i_0__ = 0; i_0__ < z_fn_i_0_max__; ++i_0__) {
            for (size_t i_1__ = 0; i_1__ < z_fn_i_1_max__; ++i_1__) {
                for (size_t i_2__ = 0; i_2__ < z_fn_i_2_max__; ++i_2__) {
                    try {
                        writer__.scalar_unconstrain(z_fn[i_0__][i_1__][i_2__]);
                    } catch (const std::exception& e) {
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable z_fn: ") + e.what()), current_statement_begin__, prog_reader__());
                    }
                }
            }
        }
        current_statement_begin__ = 31;
        if (!(context__.contains_r("a")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable a missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("a");
        pos__ = 0U;
        validate_non_negative_index("a", "nMT", nMT);
        context__.validate_dims("parameter initialization", "a", "vector_d", context__.to_vec(nMT));
        Eigen::Matrix<double, Eigen::Dynamic, 1> a(nMT);
        size_t a_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < a_j_1_max__; ++j_1__) {
            a(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, a);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable a: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 32;
        if (!(context__.contains_r("b")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable b missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("b");
        pos__ = 0U;
        validate_non_negative_index("b", "nMT", nMT);
        context__.validate_dims("parameter initialization", "b", "vector_d", context__.to_vec(nMT));
        Eigen::Matrix<double, Eigen::Dynamic, 1> b(nMT);
        size_t b_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < b_j_1_max__; ++j_1__) {
            b(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(b);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable b: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 33;
        if (!(context__.contains_r("eff")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable eff missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("eff");
        pos__ = 0U;
        validate_non_negative_index("eff", "(nMT - 1)", (nMT - 1));
        validate_non_negative_index("eff", "NF", NF);
        context__.validate_dims("parameter initialization", "eff", "vector_d", context__.to_vec(NF,(nMT - 1)));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > eff(NF, Eigen::Matrix<double, Eigen::Dynamic, 1>((nMT - 1)));
        size_t eff_j_1_max__ = (nMT - 1);
        size_t eff_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < eff_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < eff_k_0_max__; ++k_0__) {
                eff[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t eff_i_0_max__ = NF;
        for (size_t i_0__ = 0; i_0__ < eff_i_0_max__; ++i_0__) {
            try {
                writer__.vector_unconstrain(eff[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable eff: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 23;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> alpha;
            (void) alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha = in__.vector_constrain(NF, lp__);
            else
                alpha = in__.vector_constrain(NF);
            current_statement_begin__ = 24;
            local_scalar_t__ mu_fn;
            (void) mu_fn;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_fn = in__.scalar_constrain(lp__);
            else
                mu_fn = in__.scalar_constrain();
            current_statement_begin__ = 25;
            local_scalar_t__ log_sig_fn;
            (void) log_sig_fn;  // dummy to suppress unused var warning
            if (jacobian__)
                log_sig_fn = in__.scalar_constrain(lp__);
            else
                log_sig_fn = in__.scalar_constrain();
            current_statement_begin__ = 26;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> log_sig_e;
            (void) log_sig_e;  // dummy to suppress unused var warning
            if (jacobian__)
                log_sig_e = in__.vector_constrain((nMT - 1), lp__);
            else
                log_sig_e = in__.vector_constrain((nMT - 1));
            current_statement_begin__ = 27;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> mu_e;
            (void) mu_e;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_e = in__.vector_constrain((nMT - 1), lp__);
            else
                mu_e = in__.vector_constrain((nMT - 1));
            current_statement_begin__ = 30;
            std::vector<std::vector<std::vector<local_scalar_t__> > > z_fn;
            size_t z_fn_d_0_max__ = NF;
            size_t z_fn_d_1_max__ = nMT;
            size_t z_fn_d_2_max__ = nrep;
            z_fn.resize(z_fn_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < z_fn_d_0_max__; ++d_0__) {
                z_fn[d_0__].resize(z_fn_d_1_max__);
                for (size_t d_1__ = 0; d_1__ < z_fn_d_1_max__; ++d_1__) {
                    z_fn[d_0__][d_1__].reserve(z_fn_d_2_max__);
                    for (size_t d_2__ = 0; d_2__ < z_fn_d_2_max__; ++d_2__) {
                        if (jacobian__)
                            z_fn[d_0__][d_1__].push_back(in__.scalar_constrain(lp__));
                        else
                            z_fn[d_0__][d_1__].push_back(in__.scalar_constrain());
                    }
                }
            }
            current_statement_begin__ = 31;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> a;
            (void) a;  // dummy to suppress unused var warning
            if (jacobian__)
                a = in__.vector_lb_constrain(0, nMT, lp__);
            else
                a = in__.vector_lb_constrain(0, nMT);
            current_statement_begin__ = 32;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> b;
            (void) b;  // dummy to suppress unused var warning
            if (jacobian__)
                b = in__.vector_constrain(nMT, lp__);
            else
                b = in__.vector_constrain(nMT);
            current_statement_begin__ = 33;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > eff;
            size_t eff_d_0_max__ = NF;
            eff.reserve(eff_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < eff_d_0_max__; ++d_0__) {
                if (jacobian__)
                    eff.push_back(in__.vector_constrain((nMT - 1), lp__));
                else
                    eff.push_back(in__.vector_constrain((nMT - 1)));
            }
            // transformed parameters
            current_statement_begin__ = 40;
            validate_non_negative_index("mu_rep_logit_fn", "NF", NF);
            validate_non_negative_index("mu_rep_logit_fn", "nMT", nMT);
            validate_non_negative_index("mu_rep_logit_fn", "nrep", nrep);
            std::vector<std::vector<std::vector<local_scalar_t__> > > mu_rep_logit_fn(NF, std::vector<std::vector<local_scalar_t__> >(nMT, std::vector<local_scalar_t__>(nrep, local_scalar_t__(0))));
            stan::math::initialize(mu_rep_logit_fn, DUMMY_VAR__);
            stan::math::fill(mu_rep_logit_fn, DUMMY_VAR__);
            current_statement_begin__ = 42;
            local_scalar_t__ sig_fn;
            (void) sig_fn;  // dummy to suppress unused var warning
            stan::math::initialize(sig_fn, DUMMY_VAR__);
            stan::math::fill(sig_fn, DUMMY_VAR__);
            stan::math::assign(sig_fn,stan::math::exp(log_sig_fn));
            current_statement_begin__ = 43;
            validate_non_negative_index("sig_e", "(nMT - 1)", (nMT - 1));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> sig_e((nMT - 1));
            stan::math::initialize(sig_e, DUMMY_VAR__);
            stan::math::fill(sig_e, DUMMY_VAR__);
            stan::math::assign(sig_e,stan::math::exp(log_sig_e));
            current_statement_begin__ = 44;
            validate_non_negative_index("sd_r_mu", "nMT", nMT);
            validate_non_negative_index("sd_r_mu", "NF", NF);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > sd_r_mu(NF, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(nMT));
            stan::math::initialize(sd_r_mu, DUMMY_VAR__);
            stan::math::fill(sd_r_mu, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 48;
            for (int i = 1; i <= NF; ++i) {
                current_statement_begin__ = 49;
                for (int j = 1; j <= nMT; ++j) {
                    current_statement_begin__ = 51;
                    stan::model::assign(sd_r_mu, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                stan::math::exp(((-(get_base1(a, j, "a", 1)) * get_base1(get_base1(Avg_Reads, i, "Avg_Reads", 1), j, "Avg_Reads", 2)) + get_base1(b, j, "b", 1))), 
                                "assigning variable sd_r_mu");
                    current_statement_begin__ = 56;
                    for (int k = 1; k <= nrep; ++k) {
                        current_statement_begin__ = 57;
                        if (as_bool(logical_eq(j, 1))) {
                            current_statement_begin__ = 58;
                            stan::model::assign(mu_rep_logit_fn, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()))), 
                                        (get_base1(alpha, i, "alpha", 1) + (get_base1(get_base1(get_base1(z_fn, i, "z_fn", 1), j, "z_fn", 2), k, "z_fn", 3) * get_base1(get_base1(sd_r_mu, i, "sd_r_mu", 1), j, "sd_r_mu", 2))), 
                                        "assigning variable mu_rep_logit_fn");
                        } else {
                            current_statement_begin__ = 60;
                            stan::model::assign(mu_rep_logit_fn, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()))), 
                                        ((get_base1(alpha, i, "alpha", 1) + get_base1(get_base1(eff, i, "eff", 1), (j - 1), "eff", 2)) + (get_base1(get_base1(get_base1(z_fn, i, "z_fn", 1), j, "z_fn", 2), k, "z_fn", 3) * get_base1(get_base1(sd_r_mu, i, "sd_r_mu", 1), j, "sd_r_mu", 2))), 
                                        "assigning variable mu_rep_logit_fn");
                        }
                    }
                }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 40;
            size_t mu_rep_logit_fn_k_0_max__ = NF;
            size_t mu_rep_logit_fn_k_1_max__ = nMT;
            size_t mu_rep_logit_fn_k_2_max__ = nrep;
            for (size_t k_0__ = 0; k_0__ < mu_rep_logit_fn_k_0_max__; ++k_0__) {
                for (size_t k_1__ = 0; k_1__ < mu_rep_logit_fn_k_1_max__; ++k_1__) {
                    for (size_t k_2__ = 0; k_2__ < mu_rep_logit_fn_k_2_max__; ++k_2__) {
                        if (stan::math::is_uninitialized(mu_rep_logit_fn[k_0__][k_1__][k_2__])) {
                            std::stringstream msg__;
                            msg__ << "Undefined transformed parameter: mu_rep_logit_fn" << "[" << k_0__ << "]" << "[" << k_1__ << "]" << "[" << k_2__ << "]";
                            stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable mu_rep_logit_fn: ") + msg__.str()), current_statement_begin__, prog_reader__());
                        }
                    }
                }
            }
            current_statement_begin__ = 42;
            if (stan::math::is_uninitialized(sig_fn)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: sig_fn";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sig_fn: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            check_greater_or_equal(function__, "sig_fn", sig_fn, 0);
            current_statement_begin__ = 43;
            size_t sig_e_j_1_max__ = (nMT - 1);
            for (size_t j_1__ = 0; j_1__ < sig_e_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(sig_e(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: sig_e" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sig_e: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "sig_e", sig_e, 0);
            current_statement_begin__ = 44;
            size_t sd_r_mu_k_0_max__ = NF;
            size_t sd_r_mu_j_1_max__ = nMT;
            for (size_t k_0__ = 0; k_0__ < sd_r_mu_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < sd_r_mu_j_1_max__; ++j_1__) {
                    if (stan::math::is_uninitialized(sd_r_mu[k_0__](j_1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: sd_r_mu" << "[" << k_0__ << "]" << "(" << j_1__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sd_r_mu: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            size_t sd_r_mu_i_0_max__ = NF;
            for (size_t i_0__ = 0; i_0__ < sd_r_mu_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "sd_r_mu[i_0__]", sd_r_mu[i_0__], 0);
            }
            // model body
            current_statement_begin__ = 70;
            lp_accum__.add(normal_log<propto__>(mu_fn, 0, 1.5));
            current_statement_begin__ = 71;
            lp_accum__.add(normal_log<propto__>(log_sig_fn, -(1), 1));
            current_statement_begin__ = 72;
            lp_accum__.add(normal_log<propto__>(alpha, mu_fn, sig_fn));
            current_statement_begin__ = 74;
            lp_accum__.add(normal_log<propto__>(log_sig_e, -(1), 1));
            current_statement_begin__ = 75;
            lp_accum__.add(normal_log<propto__>(mu_e, 0, 1));
            current_statement_begin__ = 77;
            lp_accum__.add(normal_log<propto__>(a, 0.6, 0.25));
            current_statement_begin__ = 78;
            lp_accum__.add(normal_log<propto__>(b, 0, 0.5));
            current_statement_begin__ = 81;
            for (int i = 1; i <= NF; ++i) {
                current_statement_begin__ = 85;
                for (int j = 1; j <= nMT; ++j) {
                    current_statement_begin__ = 88;
                    if (as_bool(logical_gt(j, 1))) {
                        current_statement_begin__ = 89;
                        lp_accum__.add(normal_log<propto__>(get_base1(get_base1(eff, i, "eff", 1), (j - 1), "eff", 2), get_base1(mu_e, (j - 1), "mu_e", 1), get_base1(sig_e, (j - 1), "sig_e", 1)));
                    }
                    current_statement_begin__ = 92;
                    for (int k = 1; k <= nrep; ++k) {
                        current_statement_begin__ = 93;
                        lp_accum__.add(normal_log<propto__>(get_base1(get_base1(get_base1(z_fn, i, "z_fn", 1), j, "z_fn", 2), k, "z_fn", 3), 0, 1));
                    }
                }
            }
            current_statement_begin__ = 99;
            for (int i = 1; i <= NE; ++i) {
                current_statement_begin__ = 100;
                lp_accum__.add(normal_log<propto__>(get_base1(logit_fn_rep, i, "logit_fn_rep", 1), get_base1(get_base1(get_base1(mu_rep_logit_fn, get_base1(FE, i, "FE", 1), "mu_rep_logit_fn", 1), get_base1(MT, i, "MT", 1), "mu_rep_logit_fn", 2), get_base1(R, i, "R", 1), "mu_rep_logit_fn", 3), get_base1(fn_se, i, "fn_se", 1)));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("alpha");
        names__.push_back("mu_fn");
        names__.push_back("log_sig_fn");
        names__.push_back("log_sig_e");
        names__.push_back("mu_e");
        names__.push_back("z_fn");
        names__.push_back("a");
        names__.push_back("b");
        names__.push_back("eff");
        names__.push_back("mu_rep_logit_fn");
        names__.push_back("sig_fn");
        names__.push_back("sig_e");
        names__.push_back("sd_r_mu");
        names__.push_back("kd");
        names__.push_back("L2FC_kd");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(NF);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((nMT - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((nMT - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NF);
        dims__.push_back(nMT);
        dims__.push_back(nrep);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(nMT);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(nMT);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NF);
        dims__.push_back((nMT - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NF);
        dims__.push_back(nMT);
        dims__.push_back(nrep);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((nMT - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NF);
        dims__.push_back(nMT);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NF);
        dims__.push_back(nMT);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NF);
        dims__.push_back((nMT - 1));
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_Pooled_Hybrid_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha = in__.vector_constrain(NF);
        size_t alpha_j_1_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            vars__.push_back(alpha(j_1__));
        }
        double mu_fn = in__.scalar_constrain();
        vars__.push_back(mu_fn);
        double log_sig_fn = in__.scalar_constrain();
        vars__.push_back(log_sig_fn);
        Eigen::Matrix<double, Eigen::Dynamic, 1> log_sig_e = in__.vector_constrain((nMT - 1));
        size_t log_sig_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < log_sig_e_j_1_max__; ++j_1__) {
            vars__.push_back(log_sig_e(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> mu_e = in__.vector_constrain((nMT - 1));
        size_t mu_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < mu_e_j_1_max__; ++j_1__) {
            vars__.push_back(mu_e(j_1__));
        }
        std::vector<std::vector<std::vector<double> > > z_fn;
        size_t z_fn_d_0_max__ = NF;
        size_t z_fn_d_1_max__ = nMT;
        size_t z_fn_d_2_max__ = nrep;
        z_fn.resize(z_fn_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < z_fn_d_0_max__; ++d_0__) {
            z_fn[d_0__].resize(z_fn_d_1_max__);
            for (size_t d_1__ = 0; d_1__ < z_fn_d_1_max__; ++d_1__) {
                z_fn[d_0__][d_1__].reserve(z_fn_d_2_max__);
                for (size_t d_2__ = 0; d_2__ < z_fn_d_2_max__; ++d_2__) {
                    z_fn[d_0__][d_1__].push_back(in__.scalar_constrain());
                }
            }
        }
        size_t z_fn_k_0_max__ = NF;
        size_t z_fn_k_1_max__ = nMT;
        size_t z_fn_k_2_max__ = nrep;
        for (size_t k_2__ = 0; k_2__ < z_fn_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < z_fn_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < z_fn_k_0_max__; ++k_0__) {
                    vars__.push_back(z_fn[k_0__][k_1__][k_2__]);
                }
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> a = in__.vector_lb_constrain(0, nMT);
        size_t a_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < a_j_1_max__; ++j_1__) {
            vars__.push_back(a(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> b = in__.vector_constrain(nMT);
        size_t b_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < b_j_1_max__; ++j_1__) {
            vars__.push_back(b(j_1__));
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > eff;
        size_t eff_d_0_max__ = NF;
        eff.reserve(eff_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < eff_d_0_max__; ++d_0__) {
            eff.push_back(in__.vector_constrain((nMT - 1)));
        }
        size_t eff_j_1_max__ = (nMT - 1);
        size_t eff_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < eff_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < eff_k_0_max__; ++k_0__) {
                vars__.push_back(eff[k_0__](j_1__));
            }
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 40;
            validate_non_negative_index("mu_rep_logit_fn", "NF", NF);
            validate_non_negative_index("mu_rep_logit_fn", "nMT", nMT);
            validate_non_negative_index("mu_rep_logit_fn", "nrep", nrep);
            std::vector<std::vector<std::vector<double> > > mu_rep_logit_fn(NF, std::vector<std::vector<double> >(nMT, std::vector<double>(nrep, double(0))));
            stan::math::initialize(mu_rep_logit_fn, DUMMY_VAR__);
            stan::math::fill(mu_rep_logit_fn, DUMMY_VAR__);
            current_statement_begin__ = 42;
            double sig_fn;
            (void) sig_fn;  // dummy to suppress unused var warning
            stan::math::initialize(sig_fn, DUMMY_VAR__);
            stan::math::fill(sig_fn, DUMMY_VAR__);
            stan::math::assign(sig_fn,stan::math::exp(log_sig_fn));
            current_statement_begin__ = 43;
            validate_non_negative_index("sig_e", "(nMT - 1)", (nMT - 1));
            Eigen::Matrix<double, Eigen::Dynamic, 1> sig_e((nMT - 1));
            stan::math::initialize(sig_e, DUMMY_VAR__);
            stan::math::fill(sig_e, DUMMY_VAR__);
            stan::math::assign(sig_e,stan::math::exp(log_sig_e));
            current_statement_begin__ = 44;
            validate_non_negative_index("sd_r_mu", "nMT", nMT);
            validate_non_negative_index("sd_r_mu", "NF", NF);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > sd_r_mu(NF, Eigen::Matrix<double, Eigen::Dynamic, 1>(nMT));
            stan::math::initialize(sd_r_mu, DUMMY_VAR__);
            stan::math::fill(sd_r_mu, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 48;
            for (int i = 1; i <= NF; ++i) {
                current_statement_begin__ = 49;
                for (int j = 1; j <= nMT; ++j) {
                    current_statement_begin__ = 51;
                    stan::model::assign(sd_r_mu, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                stan::math::exp(((-(get_base1(a, j, "a", 1)) * get_base1(get_base1(Avg_Reads, i, "Avg_Reads", 1), j, "Avg_Reads", 2)) + get_base1(b, j, "b", 1))), 
                                "assigning variable sd_r_mu");
                    current_statement_begin__ = 56;
                    for (int k = 1; k <= nrep; ++k) {
                        current_statement_begin__ = 57;
                        if (as_bool(logical_eq(j, 1))) {
                            current_statement_begin__ = 58;
                            stan::model::assign(mu_rep_logit_fn, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()))), 
                                        (get_base1(alpha, i, "alpha", 1) + (get_base1(get_base1(get_base1(z_fn, i, "z_fn", 1), j, "z_fn", 2), k, "z_fn", 3) * get_base1(get_base1(sd_r_mu, i, "sd_r_mu", 1), j, "sd_r_mu", 2))), 
                                        "assigning variable mu_rep_logit_fn");
                        } else {
                            current_statement_begin__ = 60;
                            stan::model::assign(mu_rep_logit_fn, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()))), 
                                        ((get_base1(alpha, i, "alpha", 1) + get_base1(get_base1(eff, i, "eff", 1), (j - 1), "eff", 2)) + (get_base1(get_base1(get_base1(z_fn, i, "z_fn", 1), j, "z_fn", 2), k, "z_fn", 3) * get_base1(get_base1(sd_r_mu, i, "sd_r_mu", 1), j, "sd_r_mu", 2))), 
                                        "assigning variable mu_rep_logit_fn");
                        }
                    }
                }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 42;
            check_greater_or_equal(function__, "sig_fn", sig_fn, 0);
            current_statement_begin__ = 43;
            check_greater_or_equal(function__, "sig_e", sig_e, 0);
            current_statement_begin__ = 44;
            size_t sd_r_mu_i_0_max__ = NF;
            for (size_t i_0__ = 0; i_0__ < sd_r_mu_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "sd_r_mu[i_0__]", sd_r_mu[i_0__], 0);
            }
            // write transformed parameters
            if (include_tparams__) {
                size_t mu_rep_logit_fn_k_0_max__ = NF;
                size_t mu_rep_logit_fn_k_1_max__ = nMT;
                size_t mu_rep_logit_fn_k_2_max__ = nrep;
                for (size_t k_2__ = 0; k_2__ < mu_rep_logit_fn_k_2_max__; ++k_2__) {
                    for (size_t k_1__ = 0; k_1__ < mu_rep_logit_fn_k_1_max__; ++k_1__) {
                        for (size_t k_0__ = 0; k_0__ < mu_rep_logit_fn_k_0_max__; ++k_0__) {
                            vars__.push_back(mu_rep_logit_fn[k_0__][k_1__][k_2__]);
                        }
                    }
                }
                vars__.push_back(sig_fn);
                size_t sig_e_j_1_max__ = (nMT - 1);
                for (size_t j_1__ = 0; j_1__ < sig_e_j_1_max__; ++j_1__) {
                    vars__.push_back(sig_e(j_1__));
                }
                size_t sd_r_mu_j_1_max__ = nMT;
                size_t sd_r_mu_k_0_max__ = NF;
                for (size_t j_1__ = 0; j_1__ < sd_r_mu_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < sd_r_mu_k_0_max__; ++k_0__) {
                        vars__.push_back(sd_r_mu[k_0__](j_1__));
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 112;
            validate_non_negative_index("kd", "nMT", nMT);
            validate_non_negative_index("kd", "NF", NF);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > kd(NF, Eigen::Matrix<double, Eigen::Dynamic, 1>(nMT));
            stan::math::initialize(kd, DUMMY_VAR__);
            stan::math::fill(kd, DUMMY_VAR__);
            current_statement_begin__ = 113;
            validate_non_negative_index("L2FC_kd", "(nMT - 1)", (nMT - 1));
            validate_non_negative_index("L2FC_kd", "NF", NF);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > L2FC_kd(NF, Eigen::Matrix<double, Eigen::Dynamic, 1>((nMT - 1)));
            stan::math::initialize(L2FC_kd, DUMMY_VAR__);
            stan::math::fill(L2FC_kd, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 115;
            for (int i = 1; i <= NF; ++i) {
                current_statement_begin__ = 116;
                for (int j = 1; j <= nMT; ++j) {
                    current_statement_begin__ = 117;
                    if (as_bool(logical_eq(j, 1))) {
                        current_statement_begin__ = 118;
                        stan::model::assign(kd, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                    (-(stan::math::log((1 - inv_logit(get_base1(alpha, i, "alpha", 1))))) / get_base1(tl, j, "tl", 1)), 
                                    "assigning variable kd");
                    } else {
                        current_statement_begin__ = 120;
                        stan::model::assign(kd, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                    (-(stan::math::log((1 - inv_logit((get_base1(alpha, i, "alpha", 1) + get_base1(get_base1(eff, i, "eff", 1), (j - 1), "eff", 2)))))) / get_base1(tl, j, "tl", 1)), 
                                    "assigning variable kd");
                    }
                }
                current_statement_begin__ = 123;
                for (int j = 1; j <= (nMT - 1); ++j) {
                    current_statement_begin__ = 124;
                    stan::model::assign(L2FC_kd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                stan::math::log2((get_base1(get_base1(kd, i, "kd", 1), (j + 1), "kd", 2) / get_base1(get_base1(kd, i, "kd", 1), 1, "kd", 2))), 
                                "assigning variable L2FC_kd");
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 112;
            size_t kd_j_1_max__ = nMT;
            size_t kd_k_0_max__ = NF;
            for (size_t j_1__ = 0; j_1__ < kd_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < kd_k_0_max__; ++k_0__) {
                    vars__.push_back(kd[k_0__](j_1__));
                }
            }
            current_statement_begin__ = 113;
            size_t L2FC_kd_j_1_max__ = (nMT - 1);
            size_t L2FC_kd_k_0_max__ = NF;
            for (size_t j_1__ = 0; j_1__ < L2FC_kd_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < L2FC_kd_k_0_max__; ++k_0__) {
                    vars__.push_back(L2FC_kd[k_0__](j_1__));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_Pooled_Hybrid";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t alpha_j_1_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_fn";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "log_sig_fn";
        param_names__.push_back(param_name_stream__.str());
        size_t log_sig_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < log_sig_e_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_sig_e" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mu_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < mu_e_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu_e" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t z_fn_k_0_max__ = NF;
        size_t z_fn_k_1_max__ = nMT;
        size_t z_fn_k_2_max__ = nrep;
        for (size_t k_2__ = 0; k_2__ < z_fn_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < z_fn_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < z_fn_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "z_fn" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t a_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < a_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "a" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t b_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < b_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "b" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t eff_j_1_max__ = (nMT - 1);
        size_t eff_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < eff_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < eff_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "eff" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t mu_rep_logit_fn_k_0_max__ = NF;
            size_t mu_rep_logit_fn_k_1_max__ = nMT;
            size_t mu_rep_logit_fn_k_2_max__ = nrep;
            for (size_t k_2__ = 0; k_2__ < mu_rep_logit_fn_k_2_max__; ++k_2__) {
                for (size_t k_1__ = 0; k_1__ < mu_rep_logit_fn_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < mu_rep_logit_fn_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "mu_rep_logit_fn" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "sig_fn";
            param_names__.push_back(param_name_stream__.str());
            size_t sig_e_j_1_max__ = (nMT - 1);
            for (size_t j_1__ = 0; j_1__ < sig_e_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "sig_e" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t sd_r_mu_j_1_max__ = nMT;
            size_t sd_r_mu_k_0_max__ = NF;
            for (size_t j_1__ = 0; j_1__ < sd_r_mu_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < sd_r_mu_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "sd_r_mu" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t kd_j_1_max__ = nMT;
        size_t kd_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < kd_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < kd_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "kd" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t L2FC_kd_j_1_max__ = (nMT - 1);
        size_t L2FC_kd_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < L2FC_kd_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < L2FC_kd_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "L2FC_kd" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t alpha_j_1_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_fn";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "log_sig_fn";
        param_names__.push_back(param_name_stream__.str());
        size_t log_sig_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < log_sig_e_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_sig_e" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mu_e_j_1_max__ = (nMT - 1);
        for (size_t j_1__ = 0; j_1__ < mu_e_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu_e" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t z_fn_k_0_max__ = NF;
        size_t z_fn_k_1_max__ = nMT;
        size_t z_fn_k_2_max__ = nrep;
        for (size_t k_2__ = 0; k_2__ < z_fn_k_2_max__; ++k_2__) {
            for (size_t k_1__ = 0; k_1__ < z_fn_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < z_fn_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "z_fn" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t a_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < a_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "a" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t b_j_1_max__ = nMT;
        for (size_t j_1__ = 0; j_1__ < b_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "b" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t eff_j_1_max__ = (nMT - 1);
        size_t eff_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < eff_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < eff_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "eff" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t mu_rep_logit_fn_k_0_max__ = NF;
            size_t mu_rep_logit_fn_k_1_max__ = nMT;
            size_t mu_rep_logit_fn_k_2_max__ = nrep;
            for (size_t k_2__ = 0; k_2__ < mu_rep_logit_fn_k_2_max__; ++k_2__) {
                for (size_t k_1__ = 0; k_1__ < mu_rep_logit_fn_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < mu_rep_logit_fn_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "mu_rep_logit_fn" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << k_2__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "sig_fn";
            param_names__.push_back(param_name_stream__.str());
            size_t sig_e_j_1_max__ = (nMT - 1);
            for (size_t j_1__ = 0; j_1__ < sig_e_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "sig_e" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t sd_r_mu_j_1_max__ = nMT;
            size_t sd_r_mu_k_0_max__ = NF;
            for (size_t j_1__ = 0; j_1__ < sd_r_mu_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < sd_r_mu_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "sd_r_mu" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t kd_j_1_max__ = nMT;
        size_t kd_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < kd_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < kd_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "kd" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t L2FC_kd_j_1_max__ = (nMT - 1);
        size_t L2FC_kd_k_0_max__ = NF;
        for (size_t j_1__ = 0; j_1__ < L2FC_kd_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < L2FC_kd_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "L2FC_kd" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
}; // model
}  // namespace
typedef model_Pooled_Hybrid_namespace::model_Pooled_Hybrid stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
